// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IPiercingShotSystem {
  function piercingshot(bytes32 cardKey, uint32 newX, uint32 newY) external;
}
